#!/usr/bin/env php
<?php
require __DIR__ . '/vendor/autoload.php';

$dotenv = new Dotenv\Dotenv(__DIR__, '.env');
$dotenv->load();

date_default_timezone_set('America/Montreal');


use ThreenityCMS\Commands\Database\Dump;
use ThreenityCMS\Commands\Database\Import;
use ThreenityCMS\Commands\Groups\ListGroup;
use ThreenityCMS\Commands\Models\CreateModel;
use ThreenityCMS\Commands\Modules\CreateModule;
use ThreenityCMS\Commands\Modules\RegisterModules;
use ThreenityCMS\Commands\Rbac\AssignmentRbac;
use ThreenityCMS\Commands\Rbac\AssignRbac;
use ThreenityCMS\Commands\Rbac\CreateRbac;
use ThreenityCMS\Commands\Rbac\DeassignRbac;
use ThreenityCMS\Commands\Rbac\ListRbac;
use Symfony\Component\Console\Application;

/** @var $application - New application */
$application = new Application("Threenity CMS console", "1.0.0");

/** Module */
$application->add(new CreateModule());
$application->add(new RegisterModules());

/** Model */
$application->add(new CreateModel());

/** RBAC */
$application->add(new CreateRbac());
$application->add(new ListRbac());
$application->add(new AssignRbac());
$application->add(new DeassignRbac());
$application->add(new AssignmentRbac());

/** GROUP */
$application->add(new ListGroup());

/** DATABASE */
$application->add(new Dump());
$application->add(new Import());

/** Run application */
$application->run();